In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [5]:
df = pd.read_csv("../../datasets/Social_Network_Ads.csv")

In [6]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
df.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [8]:
df = df.iloc[:,2:]

In [9]:
df.sample(5)

     Age  EstimatedSalary  Purchased
124   41            51000          0
11    26            52000          0
141   18            68000          0
28    29            43000          0
189   28            32000          0

TRAIN TEST SPLIT

In [10]:
X= df.drop(columns = ['Purchased'])
y = df['Purchased']

In [11]:
X.head()

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state = 0)

X_train.shape, y_train.shape

((320, 2), (320,))

In [15]:
from sklearn.preprocessing import StandardScaler

#StandardScaler is not a function instead it is a class
scaler = StandardScaler()

#Fit the scaler into the values - Understands the dataset and learns the values like the mean and standard deviation
scaler.fit(X_train)

#Transforming both the training set and the testing set
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
scaler.mean_

array([3.8218750e+01, 6.9928125e+04])

In [17]:
X_train

     Age  EstimatedSalary
336   58           144000
64    59            83000
55    24            55000
106   26            35000
300   58            38000
..   ...              ...
323   48            30000
192   29            43000
117   36            52000
47    27            54000
172   26           118000

[320 rows x 2 columns]

In [18]:
X_train_scaled

array([[ 1.92295008e+00,  2.14601566e+00],
       [ 2.02016082e+00,  3.78719297e-01],
       [-1.38221530e+00, -4.32498705e-01],
       [-1.18779381e+00, -1.01194013e+00],
       [ 1.92295008e+00, -9.25023920e-01],
       [ 3.67578135e-01,  2.91803083e-01],
       [ 1.73156642e-01,  1.46942725e-01],
       [ 2.02016082e+00,  1.74040666e+00],
       [ 7.56421121e-01, -8.38107706e-01],
       [ 2.70367388e-01, -2.87638347e-01],
       [ 3.67578135e-01, -1.71750061e-01],
       [-1.18475597e-01,  2.20395980e+00],
       [-1.47942605e+00, -6.35303205e-01],
       [-1.28500455e+00, -1.06988428e+00],
       [-1.38221530e+00,  4.07691369e-01],
       [-1.09058306e+00,  7.55356227e-01],
       [-1.47942605e+00, -2.00722133e-01],
       [ 9.50842613e-01, -1.06988428e+00],
       [ 9.50842613e-01,  5.81523798e-01],
       [ 3.67578135e-01,  9.87132798e-01],
       [ 5.61999628e-01, -8.96051849e-01],
       [-6.04529329e-01,  1.45068594e+00],
       [-2.12648508e-02, -5.77359062e-01],
       [-6.04529329e-01,  1.88526701e+00],
       [ 1.33968560e+00, -1.41754914e+00],
       [ 1.43689635e+00,  9.87132798e-01],
       [ 7.59458956e-02, -8.09135634e-01],
       [-2.12648508e-02, -2.58666276e-01],
       [-2.15686344e-01, -5.77359062e-01],
       [-2.15686344e-01, -2.00722133e-01],
       [-3.12897090e-01, -1.30166085e+00],
       [-3.12897090e-01, -5.77359062e-01],
       [ 3.67578135e-01,  8.89985821e-02],
       [ 8.53631867e-01, -6.06331134e-01],
       [ 2.02016082e+00, -1.18577256e+00],
       [ 1.04805336e+00, -1.42777990e-01],
       [ 6.59210374e-01,  1.76937873e+00],
       [-7.01740076e-01,  5.52551726e-01],
       [ 7.56421121e-01,  3.49747226e-01],
       [ 8.53631867e-01, -5.48386991e-01],
       [-1.18779381e+00, -1.59138156e+00],
       [ 2.11737157e+00,  9.29188655e-01],
       [-2.12648508e-02,  1.21890937e+00],
       [ 1.73156642e-01,  1.07404901e+00],
       [ 3.67578135e-01, -4.90442848e-01],
       [-3.12897090e-01, -3.16610419e-01],
       [ 9.50842613e-01, -8.38107706e-01],
       [ 9.50842613e-01,  1.85629494e+00],
       [-2.12648508e-02,  1.24788144e+00],
       [-8.96161568e-01,  2.26190394e+00],
       [-1.18779381e+00, -1.59138156e+00],
       [ 2.11737157e+00, -8.09135634e-01],
       [-1.38221530e+00, -1.47549328e+00],
       [ 3.67578135e-01,  2.29087602e+00],
       [ 7.56421121e-01,  7.55356227e-01],
       [-9.93372315e-01, -3.16610419e-01],
       [ 7.59458956e-02,  7.55356227e-01],
       [-9.93372315e-01,  5.52551726e-01],
       [ 2.70367388e-01,  6.00265106e-02],
       [ 6.59210374e-01, -1.27268878e+00],
       [-5.07318583e-01, -2.68897039e-02],
       [-1.77105829e+00,  3.49747226e-01],
       [-7.01740076e-01,  1.17970654e-01],
       [ 3.67578135e-01,  2.91803083e-01],
       [-3.12897090e-01,  6.00265106e-02],
       [-5.07318583e-01,  2.29087602e+00],
       [ 1.73156642e-01,  3.10544391e-02],
       [ 1.24247485e+00,  2.20395980e+00],
       [ 7.56421121e-01,  2.62831011e-01],
       [-3.12897090e-01,  1.46942725e-01],
       [-2.12648508e-02, -5.48386991e-01],
       [-2.15686344e-01,  1.46942725e-01],
       [-1.18475597e-01,  2.33858940e-01],
       [-2.12648508e-02, -2.58666276e-01],
       [ 2.11737157e+00,  1.10302108e+00],
       [-1.77105829e+00,  3.49747226e-01],
       [ 1.82573933e+00,  1.17970654e-01],
       [ 3.67578135e-01, -1.42777990e-01],
       [-1.18779381e+00,  2.91803083e-01],
       [ 7.56421121e-01,  1.36376973e+00],
       [-3.12897090e-01, -2.58666276e-01],
       [-1.67384754e+00, -5.58617754e-02],
       [-9.93372315e-01, -7.51191491e-01],
       [ 2.70367388e-01,  4.94607583e-01],
       [-1.18475597e-01, -1.06988428e+00],
       [-1.09058306e+00,  5.81523798e-01],
       [ 7.59458956e-02, -8.09135634e-01],
       [-9.93372315e-01,  1.53760216e+00],
       [-7.01740076e-01,  1.39274180e+00],
       [-1.28500455e+00,  4.94607583e-01],
       [-3.12897090e-01,  3.10544391e-02],
       [-1.18475597e-01,  2.08236764e-03],
       [-3.12897090e-01, -8.96051849e-01],
       [ 8.53631867e-01, -1.35960499e+00],
       [-3.12897090e-01,  2.23293187e+00],
       [ 9.50842613e-01,  1.97218323e+00],
       [-1.18779381e+00,  4.65635512e-01],
       [-1.28500455e+00,  2.62831011e-01],
       [ 1.33968560e+00,  1.97218323e+00],
       [ 1.24247485e+00, -1.35960499e+00],
       [-3.12897090e-01, -2.87638347e-01],
       [-5.07318583e-01,  1.24788144e+00],
       [-7.98950822e-01,  1.07404901e+00],
       [ 9.50842613e-01, -1.06988428e+00],
       [ 2.70367388e-01,  2.91803083e-01],
       [ 9.50842613e-01,  7.55356227e-01],
       [-7.01740076e-01, -1.50446535e+00],
       [-7.01740076e-01,  3.10544391e-02],
       [ 4.64788881e-01,  1.71143459e+00],
       [ 2.02016082e+00,  1.75914797e-01],
       [-1.96547978e+00, -7.51191491e-01],
       [-2.15686344e-01,  1.39274180e+00],
       [ 3.67578135e-01,  5.81523798e-01],
       [ 8.53631867e-01, -1.15680049e+00],
       [-1.18779381e+00, -7.80163563e-01],
       [ 1.73156642e-01,  2.33858940e-01],
       [ 7.56421121e-01, -3.16610419e-01],
       [ 2.02016082e+00, -8.09135634e-01],
       [ 7.56421121e-01,  1.17970654e-01],
       [-3.12897090e-01,  6.10495869e-01],
       [-9.93372315e-01, -3.16610419e-01],
       [ 1.73156642e-01, -3.74554562e-01],
       [ 2.02016082e+00,  2.11704359e+00],
       [ 1.82573933e+00, -1.27268878e+00],
       [ 1.33968560e+00, -9.25023920e-01],
       [ 8.53631867e-01,  1.24788144e+00],
       [ 1.43689635e+00,  2.11704359e+00],
       [-3.12897090e-01, -1.24371671e+00],
       [ 1.92295008e+00,  9.00216584e-01],
       [ 6.59210374e-01, -7.22219420e-01],
       [-1.47942605e+00,  3.49747226e-01],
       [ 7.56421121e-01, -1.35960499e+00],
       [ 3.67578135e-01, -1.42777990e-01],
       [-9.93372315e-01,  4.07691369e-01],
       [-2.12648508e-02, -3.16610419e-01],
       [-1.18779381e+00,  4.07691369e-01],
       [-8.96161568e-01, -1.21474464e+00],
       [-1.18475597e-01,  3.10544391e-02],
       [-1.57663679e+00, -4.32498705e-01],
       [ 9.50842613e-01, -1.01194013e+00],
       [ 1.04805336e+00, -1.21474464e+00],
       [-2.12648508e-02, -1.42777990e-01],
       [-1.09058306e+00, -1.53343742e+00],
       [ 7.56421121e-01, -1.21474464e+00],
       [ 9.50842613e-01,  2.05909944e+00],
       [-1.18779381e+00, -1.53343742e+00],
       [-3.12897090e-01,  7.84328298e-01],
       [ 7.59458956e-02, -3.16610419e-01],
       [-1.38221530e+00, -1.24371671e+00],
       [-6.04529329e-01, -1.50446535e+00],
       [ 7.56421121e-01,  5.23579655e-01],
       [-3.12897090e-01, -3.45582490e-01],
       [ 1.72852858e+00, -2.87638347e-01],
       [ 8.53631867e-01, -1.04091221e+00],
       [ 1.73156642e-01,  6.00265106e-02],
       [-6.04529329e-01,  8.71244512e-01],
       [-1.86826903e+00, -1.41754914e+00],
       [-1.28500455e+00,  5.81523798e-01],
       [-3.12897090e-01,  5.23579655e-01],
       [-9.93372315e-01, -1.09885635e+00],
       [ 1.14526411e+00, -1.44652121e+00],
       [ 1.73156642e-01, -3.16610419e-01],
       [ 1.14526411e+00, -7.51191491e-01],
       [-3.12897090e-01,  6.00265106e-02],
       [ 1.73156642e-01,  2.08807152e+00],
       [ 7.56421121e-01, -1.09885635e+00],
       [ 7.59458956e-02,  3.10544391e-02],
       [-1.77105829e+00,  1.17970654e-01],
       [-8.96161568e-01,  1.46942725e-01],
       [-7.01740076e-01,  1.75914797e-01],
       [ 8.53631867e-01, -1.30166085e+00],
       [ 1.73156642e-01, -2.58666276e-01],
       [-4.10107836e-01,  1.21890937e+00],
       [-2.12648508e-02,  2.91803083e-01],
       [ 3.67578135e-01,  1.46942725e-01],
       [ 8.53631867e-01, -6.64275277e-01],
       [ 7.59458956e-02,  1.46942725e-01],
       [-1.86826903e+00, -1.30166085e+00],
       [-1.18475597e-01,  2.91803083e-01],
       [-2.15686344e-01, -2.87638347e-01],
       [ 2.70367388e-01, -5.19414919e-01],
       [-2.15686344e-01,  1.59554630e+00],
       [ 9.50842613e-01, -1.18577256e+00],
       [-2.15686344e-01,  1.62451837e+00],
       [ 1.24247485e+00,  1.85629494e+00],
       [-1.09058306e+00, -3.74554562e-01],
       [-2.12648508e-02,  3.10544391e-02],
       [ 7.59458956e-02, -2.58666276e-01],
       [-1.57663679e+00, -1.24371671e+00],
       [-5.07318583e-01, -2.87638347e-01],
       [ 9.50842613e-01,  1.17970654e-01],
       [ 1.92295008e+00, -1.35960499e+00],
       [ 1.43689635e+00,  6.00265106e-02],
       [-6.04529329e-01,  1.36376973e+00],
       [ 1.53410709e+00,  2.08236764e-03],
       [-7.98950822e-01,  2.91803083e-01],
       [ 1.92295008e+00,  7.26384155e-01],
       [-1.18779381e+00, -5.19414919e-01],
       [ 6.59210374e-01,  2.62831011e-01],
       [-1.38221530e+00, -4.32498705e-01],
       [ 1.73156642e-01,  1.46942725e-01],
       [-5.07318583e-01, -1.21474464e+00],
       [ 5.61999628e-01,  2.00115530e+00],
       [-1.57663679e+00, -1.50446535e+00],
       [-5.07318583e-01, -5.48386991e-01],
       [ 4.64788881e-01,  1.82732287e+00],
       [-1.38221530e+00, -1.09885635e+00],
       [ 7.56421121e-01, -1.38857706e+00],
       [-3.12897090e-01, -4.32498705e-01],
       [ 1.53410709e+00,  9.87132798e-01],
       [ 9.50842613e-01,  1.42171387e+00],
       [-3.12897090e-01, -4.90442848e-01],
       [-1.18475597e-01,  2.14601566e+00],
       [-1.47942605e+00, -1.13805918e-01],
       [-1.18475597e-01,  1.94321116e+00],
       [-7.01740076e-01, -3.45582490e-01],
       [-5.07318583e-01, -8.38107706e-01],
       [ 6.59210374e-01, -1.38857706e+00],
       [-7.98950822e-01, -1.59138156e+00],
       [-1.86826903e+00, -1.47549328e+00],
       [ 1.04805336e+00,  1.17970654e-01],
       [ 7.59458956e-02,  1.50863009e+00],
       [-3.12897090e-01,  8.89985821e-02],
       [ 7.59458956e-02,  3.10544391e-02],
       [-1.38221530e+00, -1.35960499e+00],
       [ 2.70367388e-01,  6.00265106e-02],
       [-8.96161568e-01,  3.78719297e-01],
       [ 1.53410709e+00, -1.27268878e+00],
       [-3.12897090e-01, -7.51191491e-01],
       [-1.18475597e-01,  1.46942725e-01],
       [-8.96161568e-01, -6.64275277e-01],
       [-7.01740076e-01, -5.58617754e-02],
       [ 3.67578135e-01, -4.61470776e-01],
       [-7.98950822e-01,  1.88526701e+00],
       [ 1.33968560e+00,  1.27685351e+00],
       [ 1.14526411e+00, -9.82968063e-01],
       [ 1.72852858e+00,  1.82732287e+00],
       [-8.96161568e-01, -2.58666276e-01],
       [-7.98950822e-01,  5.52551726e-01],
       [-1.18779381e+00, -1.56240949e+00],
       [-5.07318583e-01, -1.12782842e+00],
       [ 2.70367388e-01,  6.00265106e-02],
       [-2.15686344e-01, -1.06988428e+00],
       [ 1.63131784e+00,  1.59554630e+00],
       [ 9.50842613e-01,  1.76937873e+00],
       [ 2.70367388e-01,  3.10544391e-02],
       [-7.98950822e-01, -2.29694204e-01],
       [-1.18475597e-01,  6.00265106e-02],
       [ 2.70367388e-01, -2.00722133e-01],
       [ 1.92295008e+00, -6.64275277e-01],
       [-7.98950822e-01,  1.33479766e+00],
       [-1.77105829e+00, -6.06331134e-01],
       [-1.18475597e-01,  1.17970654e-01],
       [ 2.70367388e-01, -3.16610419e-01],
       [ 1.04805336e+00,  5.52551726e-01],
       [-9.93372315e-01,  2.62831011e-01],
       [ 1.43689635e+00,  3.49747226e-01],
       [ 1.73156642e-01, -3.74554562e-01],
       [ 2.11737157e+00, -1.04091221e+00],
       [-3.12897090e-01,  1.10302108e+00],
       [-1.67384754e+00,  6.00265106e-02],
       [-2.12648508e-02,  3.10544391e-02],
       [ 7.59458956e-02,  1.04507694e+00],
       [-1.18475597e-01, -3.74554562e-01],
       [-1.18779381e+00,  6.00265106e-02],
       [-3.12897090e-01, -1.35960499e+00],
       [ 1.53410709e+00,  1.10302108e+00],
       [-7.98950822e-01, -1.53343742e+00],
       [ 7.59458956e-02,  1.85629494e+00],
       [-8.96161568e-01, -7.80163563e-01],
       [-5.07318583e-01, -7.80163563e-01],
       [-3.12897090e-01, -9.25023920e-01],
       [ 2.70367388e-01, -7.22219420e-01],
       [ 2.70367388e-01,  6.00265106e-02],
       [ 7.59458956e-02,  1.85629494e+00],
       [-1.09058306e+00,  1.94321116e+00],
       [-1.67384754e+00, -1.56240949e+00],
       [-1.18779381e+00, -1.09885635e+00],
       [-7.01740076e-01, -1.13805918e-01],
       [ 7.59458956e-02,  8.89985821e-02],
       [ 2.70367388e-01,  2.62831011e-01],
       [ 8.53631867e-01, -5.77359062e-01],
       [ 2.70367388e-01, -1.15680049e+00],
       [-1.18475597e-01,  6.68440012e-01],
       [ 2.11737157e+00, -6.93247348e-01],
       [-1.28500455e+00, -1.38857706e+00],
       [-9.93372315e-01, -9.53995992e-01],
       [-2.12648508e-02, -4.32498705e-01],
       [-2.15686344e-01, -4.61470776e-01],
       [-1.77105829e+00, -9.82968063e-01],
       [ 1.72852858e+00,  9.87132798e-01],
       [ 1.73156642e-01, -3.74554562e-01],
       [ 3.67578135e-01,  1.10302108e+00],
       [-1.77105829e+00, -1.35960499e+00],
       [ 1.73156642e-01, -1.42777990e-01],
       [ 8.53631867e-01, -1.44652121e+00],
       [-1.96547978e+00,  4.65635512e-01],
       [-3.12897090e-01,  2.62831011e-01],
       [ 1.82573933e+00, -1.06988428e+00],
       [-4.10107836e-01,  6.00265106e-02],
       [ 1.04805336e+00, -8.96051849e-01],
       [-1.09058306e+00, -1.12782842e+00],
       [-1.86826903e+00,  2.08236764e-03],
       [ 7.59458956e-02,  2.62831011e-01],
       [-1.18779381e+00,  3.20775154e-01],
       [-1.28500455e+00,  2.91803083e-01],
       [-9.93372315e-01,  4.36663440e-01],
       [ 1.63131784e+00, -8.96051849e-01],
       [ 1.14526411e+00,  5.23579655e-01],
       [ 1.04805336e+00,  5.23579655e-01],
       [ 1.33968560e+00,  2.31984809e+00],
       [-3.12897090e-01, -1.42777990e-01],
       [ 3.67578135e-01, -4.61470776e-01],
       [-4.10107836e-01, -7.80163563e-01],
       [-1.18475597e-01, -5.19414919e-01],
       [ 9.50842613e-01, -1.15680049e+00],
       [-8.96161568e-01, -7.80163563e-01],
       [-2.15686344e-01, -5.19414919e-01],
       [-1.09058306e+00, -4.61470776e-01],
       [-1.18779381e+00,  1.39274180e+00]])

In [19]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns = X_test.columns)

In [20]:
np.round(X_train.describe(),1)

         Age  EstimatedSalary
count  320.0            320.0
mean    38.2          69928.1
std     10.3          34570.1
min     18.0          15000.0
25%     30.0          43000.0
50%     38.0          69500.0
75%     46.0          88000.0
max     60.0         150000.0

In [21]:
np.round(X_train_scaled.describe(),1)

         Age  EstimatedSalary
count  320.0            320.0
mean     0.0              0.0
std      1.0              1.0
min     -2.0             -1.6
25%     -0.8             -0.8
50%     -0.0             -0.0
75%      0.8              0.5
max      2.1              2.3